### ISSUE TITLE
How to setup in heaps

### ISSUE THREAD

**Issue by edwinsyarief** [nanjizal/trilateral3#2]
Hi @nanjizal ,

Can you provide an example trilateral3 lines implementation in heaps?

I couldn't make it works.

Best regards,
Edwin

**Comment by nanjizal** [comment]
I have created this for you.
https://github.com/TrilateralX/TrilateralHeapsSVG/blob/master/README.md

Need haxe4.2, may need to manually build heaps, I have not yet tried... I might wait.

The project code does not seem to have errors, but not able to test, I have implemented it in a rather naive way.

https://github.com/TrilateralX/TrilateralHeapsBasic/blob/master/src/trilateralHeapsBasic/AppHeaps.hx#L49

Note that lower level approach might be more suitable, it's not ideal to have to loop through the array and addVertices, prefer to just pass Array as buffer.  The design is not tied to using Float32Array see Heaps2Gnodule, commented out any matrix array as I think it's not need unless an axis needs flipping.

**Comment by nanjizal** [comment]
ok it's opening a browser now...

**Comment by nanjizal** [comment]
![heapsTrilateral3](https://user-images.githubusercontent.com/20134338/84136929-dfa6c200-aa43-11ea-90a1-12268e399188.png)
It's a bit heavy this way it should be feasible to do it much better so it runs faster

**Comment by nanjizal** [comment]
there is no reason that it can't be implemented to be as fast as the lime or webgl examples.

**Comment by nanjizal** [comment]
I will close this issue, at moment I am not inclined to dig deeper, if you need me to implement the other examples in this form do let me know.

**Comment by nanjizal** [comment]
also antialias does not seem to be setup well, if you get anywhere with improving it I would be very interested, also this is 2D really I support 2.5D so that's not covered by this example.

**Comment by edwinsyarief** [comment]
I will try. Thank you very much
