### ISSUE TITLE
Is it possible to use it in openfl? I can provide some help

### ISSUE THREAD

**Issue by rainyt** [nanjizal/trilateral3#6]
Is it possible to use it in openfl? I can provide some help

**Comment by nanjizal** [comment]
https://github.com/nanjizal/cornerContourSamples/blob/main/src/cornerContourSamples/hxOpenFL/SvgExample.hx
basically trilateral3 internals are now corner contour, the differences are just use of different array structure that also stores z and some more features in trilateral3 for 3d.  in same project see other targets ( lime, nme and consider how ceramic is easier )

**Comment by nanjizal** [comment]
but if you look at orignal trilateral it also allowed openfl but getting to low level triangles is important for speed
